languageCode = "en"
languageName = "English"
weight = 1
title = "Subhasmita Swain"


[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "13 August 2002"
  copyright = "<div class='theme-text'>ख़म्मा गणी 🙏 ...</div>"

[author]
  name = "VIPUL PATIL"
  #image = "img/vipul.png"
  headline = "Aspiring DevOps Engineer"
  bio = "I write about DevOps, Augmented Reality, and best practices."
  links = [
    { x-twitter = "https://x.com/thisisvipull" },
    { linkedin = "https://www.linkedin.com/in/vipulpatil1786/" },
    { github = "https://github.com/1VIP1786" },
    { medium = "https://medium.com/@vipulpatil1786" },
    { stack-overflow = "https://stackoverflow.com/users/22463082/vipul-patil" },
    { email = "mailto:vipulpatil1786@gmail.com" },
  ]
